//! Harlequin solochain runtime — the program a node executes (packaged to WASM, forkless-upgradeable).
//!
//! Composes `frame_system` + the standard pallets a working node needs (timestamp, balances, sudo,
//! transaction-payment) + the Harlequin **reputation** pallet, via `#[frame_construct_runtime]`.
//! Consensus: starts on the minimal-template path (block authoring driven by the node — manual/instant
//! seal, no Aura/Grandpa) so a node boots and produces blocks; the **Woven-Trust** committee-by-reputation
//! engine replaces it afterwards. Sovereign chain. See `../PALLET-DESIGN.md`, SPEC §2.
//!
//! NOTE: `Sudo` (root) is a TESTNET placeholder for privileged ops and runtime upgrades; pre-mainnet it
//! MUST be replaced by reputation governance (SPEC §2.5) — a single upgrade key is a centralisation
//! backdoor (Art. VI/XII).

#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;
use alloc::vec::Vec;

/// The WASM runtime blob (generated by `build.rs`/wasm-builder). Exposed for the node's chain spec.
#[cfg(feature = "std")]
include!(concat!(env!("OUT_DIR"), "/wasm_binary.rs"));

use frame::deps::sp_genesis_builder;
use frame::prelude::*;
use frame::runtime::{apis, prelude::*};
use pallet_transaction_payment::{FeeDetails, RuntimeDispatchInfo};

/// Runtime version. `spec_version` bumps on every runtime upgrade (forkless, SPEC §2.5).
#[runtime_version]
pub const VERSION: RuntimeVersion = RuntimeVersion {
    spec_name: alloc::borrow::Cow::Borrowed("harlequin-runtime"),
    impl_name: alloc::borrow::Cow::Borrowed("harlequin-runtime"),
    authoring_version: 1,
    spec_version: 0,
    impl_version: 1,
    apis: RUNTIME_API_VERSIONS,
    transaction_version: 1,
    system_version: 1,
};

parameter_types! {
    pub const Version: RuntimeVersion = VERSION;
}

/// Transaction extensions (the checks a signed extrinsic carries).
type TxExtension = (
    frame_system::AuthorizeCall<Runtime>,
    frame_system::CheckNonZeroSender<Runtime>,
    frame_system::CheckSpecVersion<Runtime>,
    frame_system::CheckTxVersion<Runtime>,
    frame_system::CheckGenesis<Runtime>,
    frame_system::CheckEra<Runtime>,
    frame_system::CheckNonce<Runtime>,
    frame_system::CheckWeight<Runtime>,
    pallet_transaction_payment::ChargeTransactionPayment<Runtime>,
    frame_system::WeightReclaim<Runtime>,
);

type Block = frame::runtime::types_common::BlockOf<Runtime, TxExtension>;
type Header = HeaderFor<Runtime>;

type RuntimeExecutive =
    Executive<Runtime, Block, frame_system::ChainContext<Runtime>, Runtime, AllPalletsWithSystem>;

#[frame_construct_runtime]
mod runtime {
    #[runtime::runtime]
    #[runtime::derive(
        RuntimeCall,
        RuntimeEvent,
        RuntimeError,
        RuntimeOrigin,
        RuntimeTask,
        RuntimeHoldReason,
        RuntimeFreezeReason,
    )]
    pub struct Runtime;

    #[runtime::pallet_index(0)]
    pub type System = frame_system::Pallet<Runtime>;

    #[runtime::pallet_index(1)]
    pub type Reputation = pallet_reputation::Pallet<Runtime>;

    #[runtime::pallet_index(2)]
    pub type Timestamp = pallet_timestamp::Pallet<Runtime>;

    #[runtime::pallet_index(3)]
    pub type Balances = pallet_balances::Pallet<Runtime>;

    #[runtime::pallet_index(4)]
    pub type Sudo = pallet_sudo::Pallet<Runtime>;

    #[runtime::pallet_index(5)]
    pub type TransactionPayment = pallet_transaction_payment::Pallet<Runtime>;

    #[runtime::pallet_index(6)]
    pub type Manifesto = pallet_manifesto::Pallet<Runtime>;

    #[runtime::pallet_index(7)]
    pub type Justice = pallet_justice::Pallet<Runtime>;
}

#[derive_impl(frame_system::config_preludes::SolochainDefaultConfig)]
impl frame_system::Config for Runtime {
    type Block = Block;
    type Version = Version;
    type AccountData = pallet_balances::AccountData<<Runtime as pallet_balances::Config>::Balance>;
}

#[derive_impl(pallet_balances::config_preludes::TestDefaultConfig)]
impl pallet_balances::Config for Runtime {
    type AccountStore = System;
}

#[derive_impl(pallet_sudo::config_preludes::TestDefaultConfig)]
impl pallet_sudo::Config for Runtime {}

#[derive_impl(pallet_timestamp::config_preludes::TestDefaultConfig)]
impl pallet_timestamp::Config for Runtime {}

#[derive_impl(pallet_transaction_payment::config_preludes::TestDefaultConfig)]
impl pallet_transaction_payment::Config for Runtime {
    type OnChargeTransaction = pallet_transaction_payment::FungibleAdapter<Balances, ()>;
    type WeightToFee = NoFee<<Self as pallet_balances::Config>::Balance>;
    type LengthToFee = FixedFee<1, <Self as pallet_balances::Config>::Balance>;
}

// --- Reputation cadence (#30): production vs fast-testnet, selected by the `mainnet` feature. ---
/// ρ in parts-per-million for `EvidenceRetention`. Mainnet 999_052 = 24-month half-life at a daily epoch.
#[cfg(feature = "mainnet")]
const EVIDENCE_RETENTION_PARTS: u32 = 999_052;
#[cfg(not(feature = "mainnet"))]
const EVIDENCE_RETENTION_PARTS: u32 = 900_000;

parameter_types! {
    /// ρ evidence retained per epoch (§1.7 decay / Art. VI). MAINNET (#30): `from_parts(999_052)` =
    /// ρ=0.999052 = a **24-month half-life** at the daily recompute epoch (24 = the Harlequin's 2 faces +
    /// 4 suits, SPEC §1.7 / LORE). TESTNET: `0.90` so decay is visible fast in validation. Selected by the
    /// `mainnet` feature. Decays everyone, founder included.
    pub const EvidenceRetention: Permill = Permill::from_parts(EVIDENCE_RETENTION_PARTS);
    /// Sponsor answers for 25% of a protégé's loss per hop (§1.5c) — **PLACEHOLDER dial**. Gentler than the
    /// old hardcoded 50% so vouching is not pure downside (pre-freeze audit, issue #4); final value is a
    /// mutable calibration. Any value < 1 keeps the cascade convergent.
    pub const SponsorLiability: Permill = Permill::from_percent(25);
}

impl pallet_reputation::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    /// Evidence authority: root for now (testnet placeholder for the pluggable proof system → governance).
    type EvidenceOrigin = EnsureRoot<Self::AccountId>;
    type JusticeOrigin = EnsureRoot<Self::AccountId>;
    type MaxVouches = ConstU32<128>;
    type VouchQuotaK = ConstU32<3>;
    type EvidenceRetention = EvidenceRetention;
    type SponsorLiability = SponsorLiability;
    /// Blocks per reputation recompute epoch (#30). MAINNET = 14400 ≈ **1 day** at 6s/block ("the deck is
    /// recounted each dawn"; pairs with ρ for the 24-month half-life). TESTNET = 10 for fast validation.
    /// The recompute runs automatically at each boundary — no root trigger (no king). Selected by `mainnet`.
    #[cfg(feature = "mainnet")]
    type EpochLength = ConstU32<14400>;
    #[cfg(not(feature = "mainnet"))]
    type EpochLength = ConstU32<10>;
}

impl pallet_manifesto::Config for Runtime {
    /// 64 KiB ceiling for the founding constitution (a charter, not a database).
    type MaxManifestoLen = ConstU32<65536>;
}

parameter_types! {
    /// τ: expected jury size (SPEC §4 rotating panel) — PLACEHOLDER, tuned pre-mainnet with #30.
    pub const JurySize: u32 = 12;
    /// Hard cap on jurors stored per case (bounds storage / PoV).
    pub const MaxJury: u32 = 32;
    /// Max accounts explicitly flagged interested at `open_case` (bounds the exclusion list).
    pub const MaxInterested: u32 = 16;
    /// 2/3 supermajority of the DRAWN jury to find guilt (SPEC §4 "supermayoría honesta").
    pub const GuiltThreshold: Permill = Permill::from_percent(67);
    /// Sortition-weight multiplier for a depth-2-related candidate (SPEC §4i-(8); ≈10% per the
    /// Monte-Carlo: holds P(2-hop ring blocks a verdict) under ~1.5% up to an 80-strong loyal ring,
    /// without a hard cut that would shrink the pool / enable pool-poisoning). Tuned pre-mainnet.
    pub const Depth2WeightPermille: Permill = Permill::from_percent(10);
}

/// Adapter: the jury draw is weighted by the reputation pallet's consensus reputation (min across suits).
pub struct JusticeReputation;
impl pallet_justice::ReputationInspect<<Runtime as frame_system::Config>::AccountId>
    for JusticeReputation
{
    fn consensus_reputation() -> Vec<(<Runtime as frame_system::Config>::AccountId, i128)> {
        pallet_reputation::Pallet::<Runtime>::consensus_reputation()
    }
}

/// Adapter: the substantive interest test (Art. IX, the load-bearing exclusion of issue #5). `who` is
/// interested if it is a party OR directly trust-tied to one (vouch edge either direction) — `is_related`
/// returns true for `who == party` as well, so this single check covers both.
pub struct JusticeInterest;
impl pallet_justice::InterestInspect<<Runtime as frame_system::Config>::AccountId> for JusticeInterest {
    fn has_interest(
        who: &<Runtime as frame_system::Config>::AccountId,
        parties: &[<Runtime as frame_system::Config>::AccountId],
    ) -> bool {
        parties.iter().any(|p| pallet_reputation::Pallet::<Runtime>::is_related(who, p))
    }

    /// Depth (1 or 2) to the nearest party in the vouch graph, bounded by `DEPTH2_MAX_VISIT` accounts
    /// scanned (anti-DoS): justice down-weights a depth-2 ring juror by `Depth2WeightPermille`
    /// (SPEC §4i-(8)) instead of cutting them. Wired to the reputation pallet's bounded BFS.
    fn relation_depth(
        who: &<Runtime as frame_system::Config>::AccountId,
        parties: &[<Runtime as frame_system::Config>::AccountId],
    ) -> Option<u32> {
        const DEPTH2_MAX_VISIT: u32 = 512;
        pallet_reputation::Pallet::<Runtime>::relation_depth(who, parties, DEPTH2_MAX_VISIT)
    }
}

/// Adapter: a guilty verdict's only automated consequence — slash the culprit's standing in the case's
/// suit (§1.7). Cascade depth 3 (§1.5c). No force beyond this (Art. I).
pub struct JusticeSlasher;
impl pallet_justice::SlashOnVerdict<<Runtime as frame_system::Config>::AccountId> for JusticeSlasher {
    fn on_guilty(culprit: &<Runtime as frame_system::Config>::AccountId, dimension: u8, loss: u128) {
        let suit = match dimension {
            0 => pallet_reputation::Suit::Commerce,
            1 => pallet_reputation::Suit::Technical,
            2 => pallet_reputation::Suit::Judicial,
            _ => pallet_reputation::Suit::Governance,
        };
        pallet_reputation::Pallet::<Runtime>::slash_for_verdict(culprit, suit, loss, 3);
    }
}

impl pallet_justice::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type Reputation = JusticeReputation;
    type Interest = JusticeInterest;
    type Slasher = JusticeSlasher;
    type JurySize = JurySize;
    type MaxJury = MaxJury;
    type MaxInterested = MaxInterested;
    type Depth2WeightPermille = Depth2WeightPermille;
    type GuiltThreshold = GuiltThreshold;
}

/// Minimal genesis presets. Concrete genesis (founding cohort §1.4 + the manifesto sealed in block 0,
/// task #26) is defined by the chain spec in the node crate; no built-in presets yet.
mod genesis_config_presets {
    use super::*;
    /// "development" → default genesis (empty patch). Enough to BOOT and produce blocks under
    /// instant/manual seal (no validators/balances needed yet). The real founding-cohort + sealed-manifesto
    /// genesis (§1.4, #26) is built here at freeze.
    pub fn get_preset(id: &PresetId) -> Option<Vec<u8>> {
        let id: &str = id.as_ref();
        if id == sp_genesis_builder::DEV_RUNTIME_PRESET {
            // --- Founding cohort (§1.4): well-known dev accounts seeded with objective evidence in all
            // four suits, so the chain boots with members who already have standing. Reputation is
            // DERIVED from this at block 0 (the pallet's genesis recompute), never asserted. ---
            let founders = [
                "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY", // Alice
                "5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty", // Bob
                "5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y", // Charlie
                "5DAAnrj7VHTznn2AWBemMuyBwZWs6FNFjdyVXUeYum3PTXFy", // Dave
                "5HGjWAeFDfFCWPsjFQdVV2Msvz2XtMktvgocEZcCj68kUMaw", // Eve
                "5CiPPseXPECbkjWCa6MnjNokrgYjMqmKndv2rSnekmSK2DjL", // Ferdie
            ];
            let suits = ["Commerce", "Technical", "Judicial", "Governance"];
            let mut ev: Vec<alloc::string::String> = Vec::new();
            for f in founders {
                for s in suits {
                    ev.push(alloc::format!("[\"{f}\",\"{s}\",1000]"));
                }
            }
            let evidence = ev.join(",");

            // --- Dev-only: fund the founders and make Alice sudo, so a dev/test node can drive the
            // root-gated calls (advance_epoch, submit_evidence) to exercise the engine. NONE of this is in
            // the real freeze genesis (§1.4/#26): the launch chain has no sudo and no pre-funded balances. ---
            let bal = founders
                .iter()
                .map(|f| alloc::format!("[\"{f}\",1000000000000000000]"))
                .collect::<Vec<_>>()
                .join(",");
            let sudo_key = founders[0]; // Alice

            // --- Manifesto sealed into block 0 (Art. XII). Placeholder until the freeze. ---
            let text: &[u8] = b"HARLEQUIN -- founding manifesto placeholder. The final constitution is \
sealed into genesis at the freeze, after the adversarial audit (Art. XII, Permanence).";
            let bytes = text.iter().map(|b| alloc::format!("{b}")).collect::<Vec<_>>().join(",");

            let json = alloc::format!(
                "{{\"balances\":{{\"balances\":[{bal}]}},\"sudo\":{{\"key\":\"{sudo_key}\"}},\
\"reputation\":{{\"evidence\":[{evidence}]}},\"manifesto\":{{\"text\":[{bytes}]}}}}"
            );
            Some(json.into_bytes())
        } else {
            None
        }
    }
    pub fn preset_names() -> Vec<PresetId> {
        alloc::vec![PresetId::from(sp_genesis_builder::DEV_RUNTIME_PRESET)]
    }
}

/// Public-facing type aliases used by the runtime APIs and the node service.
pub mod interface {
    use super::Runtime;
    pub type AccountId = <Runtime as frame_system::Config>::AccountId;
    pub type Nonce = <Runtime as frame_system::Config>::Nonce;
    pub type Balance = <Runtime as pallet_balances::Config>::Balance;
    /// The opaque block type the node/client side operates on (opaque extrinsics).
    pub type OpaqueBlock = frame::runtime::types_common::OpaqueBlock;
}

impl_runtime_apis! {
    impl apis::Core<Block> for Runtime {
        fn version() -> RuntimeVersion {
            VERSION
        }

        fn execute_block(block: <Block as frame::traits::Block>::LazyBlock) {
            RuntimeExecutive::execute_block(block)
        }

        fn initialize_block(header: &Header) -> ExtrinsicInclusionMode {
            RuntimeExecutive::initialize_block(header)
        }
    }

    impl apis::Metadata<Block> for Runtime {
        fn metadata() -> OpaqueMetadata {
            OpaqueMetadata::new(Runtime::metadata().into())
        }

        fn metadata_at_version(version: u32) -> Option<OpaqueMetadata> {
            Runtime::metadata_at_version(version)
        }

        fn metadata_versions() -> Vec<u32> {
            Runtime::metadata_versions()
        }
    }

    impl apis::BlockBuilder<Block> for Runtime {
        fn apply_extrinsic(extrinsic: ExtrinsicFor<Runtime>) -> ApplyExtrinsicResult {
            RuntimeExecutive::apply_extrinsic(extrinsic)
        }

        fn finalize_block() -> HeaderFor<Runtime> {
            RuntimeExecutive::finalize_block()
        }

        fn inherent_extrinsics(data: InherentData) -> Vec<ExtrinsicFor<Runtime>> {
            data.create_extrinsics()
        }

        fn check_inherents(
            block: <Block as frame::traits::Block>::LazyBlock,
            data: InherentData,
        ) -> CheckInherentsResult {
            data.check_extrinsics(&block)
        }
    }

    impl apis::TaggedTransactionQueue<Block> for Runtime {
        fn validate_transaction(
            source: TransactionSource,
            tx: ExtrinsicFor<Runtime>,
            block_hash: <Runtime as frame_system::Config>::Hash,
        ) -> TransactionValidity {
            RuntimeExecutive::validate_transaction(source, tx, block_hash)
        }
    }

    impl apis::OffchainWorkerApi<Block> for Runtime {
        fn offchain_worker(header: &HeaderFor<Runtime>) {
            RuntimeExecutive::offchain_worker(header)
        }
    }

    impl apis::SessionKeys<Block> for Runtime {
        fn generate_session_keys(_owner: Vec<u8>, _seed: Option<Vec<u8>>) -> apis::OpaqueGeneratedSessionKeys {
            apis::OpaqueGeneratedSessionKeys { keys: Default::default(), proof: Default::default() }
        }

        fn decode_session_keys(
            _encoded: Vec<u8>,
        ) -> Option<Vec<(Vec<u8>, apis::KeyTypeId)>> {
            Default::default()
        }
    }

    impl apis::AccountNonceApi<Block, interface::AccountId, interface::Nonce> for Runtime {
        fn account_nonce(account: interface::AccountId) -> interface::Nonce {
            System::account_nonce(account)
        }
    }

    impl harlequin_consensus_api::HarlequinConsensusApi<Block> for Runtime {
        fn consensus_reputation() -> Vec<([u8; 32], i128)> {
            pallet_reputation::Pallet::<Runtime>::consensus_reputation()
                .into_iter()
                .map(|(acc, rep)| (acc.into(), rep))
                .collect()
        }
    }

    impl pallet_transaction_payment_rpc_runtime_api::TransactionPaymentApi<Block, interface::Balance> for Runtime {
        fn query_info(uxt: ExtrinsicFor<Runtime>, len: u32) -> RuntimeDispatchInfo<interface::Balance> {
            TransactionPayment::query_info(uxt, len)
        }
        fn query_fee_details(uxt: ExtrinsicFor<Runtime>, len: u32) -> FeeDetails<interface::Balance> {
            TransactionPayment::query_fee_details(uxt, len)
        }
        fn query_weight_to_fee(weight: Weight) -> interface::Balance {
            TransactionPayment::weight_to_fee(weight)
        }
        fn query_length_to_fee(length: u32) -> interface::Balance {
            TransactionPayment::length_to_fee(length)
        }
    }

    impl apis::GenesisBuilder<Block> for Runtime {
        fn build_state(config: Vec<u8>) -> sp_genesis_builder::Result {
            build_state::<RuntimeGenesisConfig>(config)
        }

        fn get_preset(id: &Option<PresetId>) -> Option<Vec<u8>> {
            get_preset::<RuntimeGenesisConfig>(id, self::genesis_config_presets::get_preset)
        }

        fn preset_names() -> Vec<PresetId> {
            self::genesis_config_presets::preset_names()
        }
    }
}
